/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregistrationproject;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ASUS
 */
public class Register_Window extends javax.swing.JFrame {

    /**
     * Creates new form Register_Window
     */
     ButtonGroup bg;
       MyJDBCConnection myc;
    public Register_Window() {
       
        initComponents();
        bg=new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
        jRadioButtonMale.setSelected(true);
        myc=new MyJDBCConnection();
    }
       //javax swing.ImageIcon for Resizing the image 
      String photopath=null;
       
      public  ImageIcon resizeImageI(String photopath,byte[] photo){
          ImageIcon myPhoto=null;
          if(photopath !=null){
              myPhoto=new ImageIcon(photopath);
          }else
          {
              myPhoto=new ImageIcon(photo);
          }
              Image img= myPhoto.getImage();
              Image img1=img.getScaledInstance(label_photo.getWidth(),label_photo.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon ph=new ImageIcon(img1);
              return ph;
          
          
      }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_photo = new javax.swing.JLabel();
        UploadImageButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jDateChooserDOB = new com.toedter.calendar.JDateChooser();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMobileNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordFieldConfirmPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmailid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/school (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Shivalik Cambridge College. Sec 7, Awas Vikas Colony, Sikandra, Agra.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 710, -1));
        jPanel1.add(label_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 280, 230));

        UploadImageButton.setBackground(new java.awt.Color(102, 102, 102));
        UploadImageButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        UploadImageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/attach.png"))); // NOI18N
        UploadImageButton.setText("Select Image");
        UploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UploadImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 160, 33));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setText("CLICK HERE TO LOGIN /SIGN IN (TO CLOSE REGISTERATION FORM)");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, -1, 39));

        jButtonReset.setBackground(new java.awt.Color(102, 102, 102));
        jButtonReset.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/erase-128.png"))); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 119, 40));

        jButtonRegister.setBackground(new java.awt.Color(102, 102, 102));
        jButtonRegister.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save-icon.png"))); // NOI18N
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 122, 41));

        jDateChooserDOB.setDateFormatString("dd-MM- yyyy");
        jPanel1.add(jDateChooserDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 250, 31));

        jRadioButtonFemale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtonFemale.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonFemale.setText("Female");
        jPanel1.add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Date of Birth:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jRadioButtonMale.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jRadioButtonMale.setText("Male");
        jPanel1.add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Gender:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        jTextFieldMobileNo.setText("Enter Mobile Number");
        jPanel1.add(jTextFieldMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 279, 33));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Mobile Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jPasswordFieldConfirmPass.setText("Confirm Password");
        jPanel1.add(jPasswordFieldConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 279, 32));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jPasswordFieldPass.setText("Enter Password");
        jPanel1.add(jPasswordFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 279, 31));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jTextFieldEmailid.setText("Enter Email Id");
        jPanel1.add(jTextFieldEmailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 279, 30));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Email-id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jTextFieldName.setText("Enter Full Name");
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 279, 30));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("REGISTER NEW USER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anton-sukhinov-_C2A8THeKKs-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     // the  selected image to be Displayed in label_photo
    private void UploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageButtonActionPerformed
      
        JFileChooser chooser =new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("*images","jpg","png");
        chooser.addChoosableFileFilter(fnef);
        int ans=chooser.showSaveDialog(null);
        if(ans==JFileChooser.APPROVE_OPTION){
            File selectedPhoto=chooser.getSelectedFile();
            String path=selectedPhoto.getAbsolutePath();
            label_photo.setIcon(resizeImageI(path,null));
            this.photopath=path;
        }else{
            System.out.println("Photo or Image Not Selected..... ");
            
        
            
        }
            
    }//GEN-LAST:event_UploadImageButtonActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
    //  reset all the the Swing Control 
        jTextFieldName.setText("");
        jTextFieldEmailid.setText("");
        jTextFieldMobileNo.setText("");
        jPasswordFieldPass.setText("");
        jPasswordFieldConfirmPass.setText("");
        jDateChooserDOB.setDate(null);
        bg.clearSelection();
        label_photo.setIcon(resizeImageI("",null));
        
        
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
       // Logic to save and insert the values infromation into user table
       
        String name=jTextFieldName.getText();
        String email=jTextFieldEmailid.getText();
        String pass=jPasswordFieldPass.getText();
        String CPass=jPasswordFieldConfirmPass.getText();
        String mob=jTextFieldMobileNo.getText();
        String gen="Male";
       if(jRadioButtonFemale.isSelected())
       {
           gen="Female";
       }    
         Date dob=jDateChooserDOB.getDate();
         
         
        // Apply the validation logic for checking aloo controll are empty or not
        if(name.trim().equals("") || name.trim().equals("Enter Full Name") ||
            email.trim().equals("") || email.trim().equals("Enter Email Id") ||
             pass.trim().equals("") || pass.trim().equals("Enter Password") ||
             CPass.trim().equals("") || CPass.trim().equals("Confirm Password") ||
             mob.trim().equals("") || mob.trim().equals("Enter Mobile Number"))
                
    {
       JOptionPane.showMessageDialog(null,"All Field Are Compulsory to fill."+"Kindly Check Missing Field in Registyration Foem..."); 
        
    }else if(pass.equals(CPass)){
        if (dob==null){ //Id Date Of BirthIs Not Selected
           JOptionPane.showMessageDialog(null,"Please Select / Enter Date of birth");
           jDateChooserDOB.grabFocus();
        }else{ // if EveryThing if Fine
               //All Swing Control Field Has BEen Selected 
               //Then we can save /insert /register user into database table
               JOptionPane.showMessageDialog(null,"All field are Filled ... ");
               
                // check whether email id as user id is already in use or not
            try{
               Connection con = myc.getConn();
               String chkEmail="select name FROM schoolp.users where email=?";
              PreparedStatement pst=con.prepareStatement(chkEmail);
              pst.setString(1, email);
              ResultSet rs=pst.executeQuery();
              if(rs.next()){ //email id has been already taken then we need to ask to choose another and different email id
             JOptionPane.showMessageDialog(null,"this" +email+ "Email Address has ben already Registered / taken by other user. please choose another one,,,");
             
              }
              else{
                  // save the user gegistration details to database table
                  String saveqry="insert into schoolp.users(name,email,password,mobile,"+"gender,dob,photo) values (?,?,?,?,?,?,?)";
                  pst=con.prepareStatement(saveqry);
                  pst.setString(1, name);
                  pst.setString(2, email);
                  pst.setString(3, pass);
                  pst.setString(4, mob);
                  pst.setString(5,gen);
                   SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                   String dob1=sdf.format(jDateChooserDOB.getDate());
                    pst.setString(6, dob1);
                    
                     File f=new File(photopath);
                     FileInputStream fis=new FileInputStream(f);
                     pst.setBinaryStream(7, fis,(int)f.length());
                    
                 //  InputStream is=new FileInputStream(new File(photopath));
                  // pst.setBinaryStream(7, is,(int)file.length());
                    
                    int i= pst.executeUpdate();
                    if(i>=1){
                        JOptionPane.showMessageDialog(null,name+"User Registration Successful with user id as email Id"+email);
                        jButtonResetActionPerformed(evt);
                    }
                    else{
                        
                         JOptionPane.showMessageDialog(null,name+"User Registration Failed with user id as email Id"+email+"Try again..."); 

                    } // try
                  }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,name+"User Not Inserted / Saved Exception e"+e);
               // e.printStackTrace();
            }
        }
        // DOB==null  else 
        
        
     //pass==Cpass   
    }else{
        //if password &confirm password are not same
        JOptionPane.showMessageDialog(null,"Password and Confirm password Must be Same ... "); 
        jPasswordFieldPass.setText("");
        jPasswordFieldConfirmPass.setText("");
        
    }
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed
     // to close Current registration form and Login form
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         Login_Window lw=new Login_Window();
         lw.show();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UploadImageButton;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonReset;
    private com.toedter.calendar.JDateChooser jDateChooserDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmPass;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldEmailid;
    private javax.swing.JTextField jTextFieldMobileNo;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JLabel label_photo;
    // End of variables declaration//GEN-END:variables
}
