/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregistrationproject;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Student_window extends javax.swing.JFrame {

    /**
     * Creates new form Student_window
     */
    public Student_window() {
        
        initComponents();
        fillTable();
      
    }
    
      public Connection MyJDBConnection(){
          Connection conn=null;
          try{
              Class.forName("oracle.jdbc.driver.OracleDriver");
         conn =DriverManager.getConnection("jdbc:oracle:thin:schoolp/schoolp@localhost:1521:XE","System","oracle");
        // JOptionPane.showMessageDialog(null,"Cnnection Sucessful :" );
        return conn;
          }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Error :" + e);
              return null;
              
          }
      
      }
      String photopath;
      public ImageIcon resetImageSize(String photopath,byte[]photo){
          ImageIcon myPhoto=null;
          if(photopath!=null){
          myPhoto =new ImageIcon(photopath);
      }else{
              myPhoto=new ImageIcon(photo);
         }
          Image img=myPhoto.getImage();
          Image img1=img.getScaledInstance(label_photo.getWidth(),label_photo.getHeight(),Image.SCALE_SMOOTH);
          ImageIcon ph=new ImageIcon(img1);
          return ph;
     }
      // show  and add the data to the table  
      public ArrayList<Student_Bean>retrieveData(){
           ArrayList<Student_Bean>al=null;
           al=new ArrayList<Student_Bean>();
         try{
                Connection con=MyJDBConnection();
                String qry="select * from schoolp.students";
                Statement st=con.createStatement();
                ResultSet rs =st.executeQuery(qry);
                Student_Bean student;
                while(rs.next()){
                    student=new Student_Bean(rs.getInt(1),rs.getString("name"),
                    Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getBytes("photo"));
                     al.add(student);
         }
           }catch(Exception e){
                System.out.println("Error in retrieveData method:" +e);
               
               
           }
            return al;
      }
        // fill the table 
      
             public void fillTable(){
                ArrayList<Student_Bean>al= retrieveData();
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0); //clear the table
                Object[] row=new Object[4];
                for(int i=0;i<al.size();i++)
                {
                    row[0]=al.get(i).getId();
                    row[1]=al.get(i).getName();
                    row[2]=al.get(i).getFees();
                    row[3]=al.get(i).getDob();
                    
                    model.addRow(row);
                }
             }
              
             public void showItemFieldStudent(int index){
                   jTextField_id.setText(Integer.toString(retrieveData().get(index).getId()));
                   jTextField_name.setText(retrieveData().get(index).getName());
                   jTextField_fees.setText(Float.toString(retrieveData().get(index).getFees()));
                   try{
                        java.util.Date dob=null;
                        dob=new SimpleDateFormat("dd-MM-yyyy").parse((String)retrieveData().get(index).getDob());
                        
                        jDateChooser1_dob.setDate(dob);
                       
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,"Error showItemToFieldsTeacher()"+e);
                      }
                   label_photo.setIcon(resetImageSize(null,retrieveData().get(index).getPhoto()));
             } 
      
      
      
      
      
      
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_photo = new javax.swing.JButton();
        label_photo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1_dob = new com.toedter.calendar.JDateChooser();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jButton_new = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_fees = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jLabel3.setText("Search Student Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 250, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/knowledge.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Shivalik Cambridge College. Sec 7, Awas Vikas Colony, Sikandra, Agra.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 710, 30));

        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 180, 36));

        jTable1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "STUDENT NAME", "FEES", "DATE OF BIRTH"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 1220, 163));

        jButton_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/photo-gallery.png"))); // NOI18N
        jButton_photo.setText("SELECT PHOTO");
        jButton_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_photoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 150, 41));

        label_photo.setBackground(new java.awt.Color(255, 255, 255));
        label_photo.setOpaque(true);
        jPanel1.add(label_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 225, 131));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("PHOTO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        jDateChooser1_dob.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jDateChooser1_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 167, 38));

        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-24.png"))); // NOI18N
        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 104, 30));

        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loop-arrow.png"))); // NOI18N
        jButton_update.setText("UPDATE");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 104, 30));

        jButton_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/put-in-button.png"))); // NOI18N
        jButton_save.setText("INSERT");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 104, 30));

        jButton_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        jButton_new.setText("NEW");
        jButton_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_newActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 104, 33));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("DATE OF BIRTH:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        jPanel1.add(jTextField_fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 167, 33));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("FEES:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        jPanel1.add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 167, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("STUDENT NAME:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        jPanel1.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 167, 33));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 33));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("STUDENT INFORMATION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jamie-taylor--9C3TMXwQjQ-unsplash (1).jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  //for  Selecting the photo
    private void jButton_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_photoActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser =new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("*.images","jpg","png");
        chooser.addChoosableFileFilter(fnef);
        int ans=chooser.showSaveDialog(null);
        if(ans==JFileChooser.APPROVE_OPTION){
            File selectedPhoto=chooser.getSelectedFile();
            String path=selectedPhoto.getAbsolutePath();
            label_photo.setIcon(resetImageSize(path,null));
            this.photopath=path;
        }else{
            System.out.println("Photo or Image Not Selected..... ");
            
        
            
        }
    }//GEN-LAST:event_jButton_photoActionPerformed
 // for insert the student record
    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        if(jTextField_id.getText()!=null ||
          jTextField_name!=null ||
          jTextField_fees!=null||
          jDateChooser1_dob!=null
          && photopath!=null){
            try{
                  Connection conn=MyJDBConnection();
                            String qry="insert into schoolp.students(id,name,fees,dob,photo) values"+"(?,?,?,?,?)";
                            PreparedStatement ps=conn.prepareStatement(qry);
                             ps.setInt(1,Integer.parseInt(jTextField_id.getText()));
                            ps.setString(2,jTextField_name.getText());
                            ps.setFloat(3,Float.parseFloat(jTextField_fees.getText()));
                            
                             SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                             String dob1=sdf.format(jDateChooser1_dob.getDate());
                            ps.setString(4,dob1);
                             File f=new File(photopath);
                     FileInputStream fis=new FileInputStream(f);
                     ps.setBinaryStream(5, fis,(int)f.length());
                     int res=ps.executeUpdate();
                      fillTable();
                     if (res>=1){
                         JOptionPane.showMessageDialog(null,res+ "Number Of Student " +  " Inserted into DataBase");
                  
                     }else{
                         JOptionPane.showMessageDialog(null,"Student Insertion Failed.Failed..");
                     }
                
            }catch(Exception e){
                // JOptionPane.showMessageDialog(null,"Error :" + e);
             e.printStackTrace();
            }  
             jTextField_id.setText("");
            jTextField_name.setText("");
            jTextField_fees.setText("");
            
            }else{
               JOptionPane.showMessageDialog(null,"All Fields are Compulsory.....");
                    
                    
                    
        
    }
               
              
        
         
    }//GEN-LAST:event_jButton_saveActionPerformed
     // for updating info
    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        if(jTextField_id!=null ||
          jTextField_name!=null ||
          jTextField_fees!=null||
          jDateChooser1_dob!=null) {
              String qry=null;
              PreparedStatement ps=null;
              Connection conn=MyJDBConnection();
              
              if(photopath==null){
         
            try{
                           qry="update schoolp.students set name=?,fees=?,dob=? where id=?";
                             ps=conn.prepareStatement(qry);
                            
                            ps.setString(1,jTextField_name.getText());
                            ps.setFloat(2,Float.parseFloat(jTextField_fees.getText()));
                            
                             SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                             String dob1=sdf.format(jDateChooser1_dob.getDate());
                            ps.setString(3,dob1);
                            
                              ps.setInt(4,Integer.parseInt(jTextField_id.getText()));
                           //   File f=new File(photopath);
                    // FileInputStream fis=new FileInputStream(f);
                     //ps.setBinaryStream(5, fis,(int)f.length());
                     int res=ps.executeUpdate();
                      fillTable();
                     if (res>=1){
                         JOptionPane.showMessageDialog(null,res+ "Student " +  " Update Successsfully");
                  
                     }else
                         JOptionPane.showMessageDialog(null,"Student Updatation  Failed..");
                     
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Error :" + e);
             //e.printStackTrace();
            } 
               jTextField_id.setText("");
            jTextField_name.setText("");
            jTextField_fees.setText("");
             
            
            }else{//update with photo
                   try{ 
                               File f=new File(photopath);
                               FileInputStream fis=new FileInputStream(f);
                            
                          
                           qry="update schoolp.students set name=?,fees=?,dob=?,photo=? where id=?";
                             ps=conn.prepareStatement(qry);
                            
                            ps.setString(1,jTextField_name.getText());
                            ps.setFloat(2,Float.parseFloat(jTextField_fees.getText()));
                            
                             SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                             String dob1=sdf.format(jDateChooser1_dob.getDate());
                            ps.setString(3,dob1);
                             ps.setBinaryStream(4, fis,(int)f.length()); 
                              ps.setInt(5,Integer.parseInt(jTextField_id.getText()));
                           
                     int res=ps.executeUpdate();
                      fillTable();
                     if (res>=1){
                         JOptionPane.showMessageDialog(null,res+ "Student " +  " Update Successsfully");
                  
                     }else
                         JOptionPane.showMessageDialog(null,"Student Updatation  Failed..");
                     
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Error :" + e);
             //e.printStackTrace();
            } 
               jTextField_id.setText("");
            jTextField_name.setText("");
            jTextField_fees.setText("");
             
       
             }
        }else
               JOptionPane.showMessageDialog(null,"Student Updation Failed");
    
    }//GEN-LAST:event_jButton_updateActionPerformed
      // for  Deleting student
    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
          if(jTextField_id.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"Enter Student Id");
          }else{
              try{
                   String qry="delete from schoolp.students where id=?";
                   Connection conn=MyJDBConnection();
                   PreparedStatement ps=conn.prepareStatement(qry);
                   ps.setInt(1,Integer.parseInt(jTextField_id.getText().toString()));
                   int res=ps.executeUpdate();
                    fillTable();
                   if(res>=1){
                           JOptionPane.showMessageDialog(null,"Student Deleted Succesfully....");                       
                   }else
                      JOptionPane.showMessageDialog(null,"Student Deletion failed...");
                   
                  
              }catch(Exception e){
                   JOptionPane.showMessageDialog(null,e);
                  
              }
          
          }
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ind=jTable1.getSelectedRow();
        showItemFieldStudent(ind);
        
    }//GEN-LAST:event_jTable1MouseClicked
     // to rearch the studenty bye name
    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
         ArrayList<Student_Bean>al=null;
        al=new ArrayList<Student_Bean>();
        String val=jTextField_search.getText().toString();
        
        try{
            Connection con=MyJDBConnection();
            String qry="select * from schoolp.students where name like '%"+val+"%'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(qry);
             Student_Bean student;
             while(rs.next()){
                    student=new Student_Bean(rs.getInt(1),rs.getString("name"),
                    Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getBytes("photo"));
                 al.add(student);
             }
             
          // search  student to be added to datatable
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.setRowCount(0);
                Object[] row=new Object[4];
                for(int i=0;i<al.size();i++)
                {
                    row[0]=al.get(i).getId();
                    row[1]=al.get(i).getName();
                    row[2]=al.get(i).getFees();
                    row[3]=al.get(i).getDob();
                   model.addRow(row);
                }               
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e);
            
        }
        
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jButton_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_newActionPerformed
        // TODO add your handling code here:
        
       jTextField_id.setText("");
       jTextField_name .setText("");
        jTextField_fees.setText("");
        jDateChooser1_dob.setDate(null);
       
        label_photo.setIcon(resetImageSize("",null));
        
    }//GEN-LAST:event_jButton_newActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_new;
    private javax.swing.JButton jButton_photo;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private com.toedter.calendar.JDateChooser jDateChooser1_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_fees;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_search;
    private javax.swing.JLabel label_photo;
    // End of variables declaration//GEN-END:variables
}
